chore: update configurations

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -1,39 +1,37 @@
 name: Check
+
 on:
-  push:
-    branches:
-      - main
   pull_request:
     branches:
       - main
   workflow_dispatch: {}
+
 permissions: {}
+
 defaults:
   run:
     shell: bash
+
 jobs:
   check:
     runs-on: ubuntu-latest
+
     permissions:
       contents: read
+
     steps:
       - name: Checkout
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
 
-      - name: Setup pnpm
-        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
+      - name: Setup
+        uses: ./.github/actions/setup
 
-      - name: Setup Node.js
-        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
-        with:
-          node-version: 20
-          cache: pnpm
+      - name: Check by Biome
+        run: pnpm biome ci --formatter-enabled=false --reporter=github
 
-      - name: Install dependencies
-        run: pnpm install
+      - name: Check by Prettier
+        # Allow formatting issues (exit code 1) but fail on syntax errors (exit code 2).
+        run: pnpm prettier --check '**/*.{md,yaml,yml}' || (( $? == 1 ))
 
-      - name: Check
-        run: pnpm run ci
-
-      - name: Build
-        run: pnpm build
+      - name: Check by TypeScript
+        run: pnpm tsc
